import i18n from "i18next";
import { initReactI18next } from "react-i18next";

i18n.use(initReactI18next).init({
  resources: {
    en: {
      translation: {
        title: "Welcome",
        alerts: "Alerts",
        favorites: "Favorites",
        record: "Record",
        cancel: "cancel",
        send: "send",
        phone: "Phone",
        address: "Address",
        postedOn: "Posted On",
        name: "name",
        bloodRequestForm: "Blood request form",
        bloodRequests: "Blood Requests",
        missingChildren: "Missing Children",
        bloodDonation: "Blood Donation",
        age: "age",
        childInfoForm: "Child information form",
        logout: "Logout",
        emergency: "Emergency",
        yourFavorites: "Your favorites",
        addFavorites: "Add Favorites",
        emergencyContacts: "Emergency Contacts",
        ambulance: 'Ambulance',
        police: 'Police',
        alert: 'Alert',
        violence: 'Violence',
        kidnapping: 'Kidnapping',
        fireFighter: 'Firefighter',
        introText: 'I am in danger, I need your help.',
        howTo: 'How to?',
        paragraphOne: 'A request will be send to 5 people who are near by to 500 meter to you with your real time location on google map.',
        paragraphTwo: 'Similar request have been sent to your family and friends.',
        paragraphThree: 'A call will be placed to 181 or 100.',
        paragraphFour: 'Once you activated help, all surrounding voice recording will be started till you clicked on "I AM SAFE" button or till 2 hrs after help activation.',
        paragraphFive: 'All the people who have received your help request can see your real time movement on google map till 12 hours or till you marked yourself safe.',
        paragraphSix: 'So do not forget to click "I AM SAFE" button once you feel that you are safe.',
        errorMsg: 'File upload failed',
        retryUpload: 'Retry upload',
        uploadProgress: 'Upload progress:',
        recordingUpload: 'Recording uploaded successfully. Now sending to your favorites',
        women: 'women',
        blood: 'blood',
        child: 'child',
        emergencyScreenText: 'Here You Will See The Latest News Of the Application',
        yourRequests: 'Your requests',
        childRequests: 'Child requests',
        submit: 'Submit',
        uploadImage: 'Upload Image',
        markAsFound: 'Mark as found',
      }
    },
    gu: {
      translation: {
        title: "સ્વાગત છે",
        alerts: "સંપર્ક",
        favorites: "પસંદગી",
        record: "રેકોર્ડ",
        cancel: "રદ કરો",
        send: "મોકલો",
        phone: "ફોન",
        address: "સરનામું",
        postedOn: "તારીખ",
        name: "નામ",
        bloodRequestForm: "રક્ત વિનંતી ફોર્મ",
        bloodRequests: "રક્ત વિનંતીઓ",
        missingChildren: "લાપતા બાળકો",
        bloodDonation: "રક્તદાન",
        age: "ઉંમર",
        childInfoForm: "બાળક માહિતી ફોર્મ",
        logout: "લૉગ આઉટ",
        emergency: "કટોકટી",
        yourFavorites: "તમારા મિત્રો",
        addFavorites: "મિત્રો ઉમેરો",
        emergencyContacts: "કટોકટી સંપર્કો",
        ambulance: 'દર્દીવાહિની',
        police: 'પોલીસ',
        alert: 'ચેતવણી',
        violence: 'હિંસા',
        kidnapping: 'અપહરણ',
        fireFighter: 'અગ્નિશામક',
        introText: 'હું ભયમાં છું, મને તમારી સહાયની જરૂર છે.',
        howTo: 'કઈ રીતે?',
        paragraphOne: 'ગૂગલ મેપ પર તમારા રીઅલ ટાઇમ લોકેશન સાથે 500 જેટલા લોકોની નજીક તમને વિનંતી મોકલવામાં આવશે.',
        paragraphTwo: 'આવી જ વિનંતી તમારા પરિવાર અને મિત્રોને મોકલવામાં આવી છે.',
        paragraphThree: 'એ કોલ 181 અથવા 100 માટે મૂકવામાં આવશે.',
        paragraphFour: 'એકવાર તમે સહાયને સક્રિય કરી લો, ત્યાં સુધી આજુબાજુની તમામ અવાજ રેકોર્ડિંગ શરૂ કરવામાં આવશે જ્યાં સુધી તમે "હું સલામત છું" બટન પર ક્લિક કરશો નહીં અથવા સહાય સક્રિયકરણ પછી 2 કલાક સુધી.',
        paragraphFive: 'બધા લોકો કે જેમની તમારી સહાય વિનંતી પ્રાપ્ત થઈ છે તે ગૂગલ નકશા પર 12 કલાક સુધી અથવા તમારી જાતને સલામત તરીકે ચિહ્નિત કરે ત્યાં સુધી તમારી વાસ્તવિક સમયની હિલચાલ જોઈ શકે છે.',
        paragraphSix: 'એકવાર તમને લાગે કે તમે સુરક્ષિત છો, ત્યારે "હું સલામત છું" બટનને ક્લિક કરવાનું ભૂલશો નહીં.',
        errorMsg: 'ફાઇલ અપલોડ નિષ્ફળ થયું',
        retryUpload: 'ફરીથી અપલોડ કરવાનો પ્રયાસ કરો',
        uploadProgress: 'અપલોડ પ્રગતિ:',
        recordingUpload: 'રેકોર્ડિંગ સફળતાપૂર્વક અપલોડ થઈ. હવે તમારા મનપસંદ પર મોકલવા.',
        women: 'સ્ત્રી',
        blood: 'લોહી',
        child: 'બાળક',
        emergencyScreenText: 'અહીં તમે એપ્લિકેશનના છેલ્લા સમાચાર જોશો',
        yourRequests: 'તમારી વિનંતીઓ',
        childRequests: 'બાળ વિનંતીઓ',
        submit: 'સબમિટ કરો',
        uploadImage: 'છબી અપલોડ કરો',
        markAsFound: 'મળ્યા મુજબ ચિહ્નિત કરો',
      }
    },
    hi: {
      translation: {
        title: "स्वागत हे",
        alerts: "चेतावनी",
        favorites: "पसंदीदा",
        record: "अभिलेख",
        cancel: "रद्द करना",
        send: "भेजना",
        phone: "फ़ोन",
        address: "पता",
        postedOn: "पर प्रविष्ट किया",
        name: "नाम",
        bloodRequestForm: "रक्त अनुरोध प्रपत्र",
        bloodRequests: "रक्त अनुरोध",
        missingChildren: "ग़ुम बच्चे",
        bloodDonation: "रक्त दान",
        age: "उम्र",
        childInfoForm: "बाल जानकारी प्रपत्र",
        logout: "लॉग आउट",
        emergency: "आपातकालीन",
        yourFavorites: "आपका पसंदीदा",
        addFavorites: "पसंदीदा मे समूह करना",
        emergencyContacts: "आपातकालीन संपर्क",
        ambulance: 'रोगी-वाहन',
        police: 'पुलिस',
        alert: 'चेतावनी',
        violence: 'हिंसा',
        kidnapping: 'अपहरण',
        fireFighter: 'आग बुझानेवाला',
        introText: 'मुझे खतरा है, मुझे आपकी मदद चाहिए।',
        howTo: 'कैसे?',
        paragraphOne: 'एक अनुरोध 5 लोगों को भेजा जाएगा, जो आपके पास गूगल मानचित्र पर अपने वास्तविक समय के स्थान के साथ 500 मीटर तक हैं।',
        paragraphTwo: 'इसी तरह का अनुरोध आपके परिवार और दोस्तों को भेजा गया है।',
        paragraphThree: 'कॉल को 181 या 100 पर रखा जाएगा।',
        paragraphFour: 'एक बार आपने मदद सक्रिय कर दी, जब तक कि आप "मैं सुरक्षित हूँ" बटन पर क्लिक नहीं करते हैं या मदद सक्रियण के बाद 2 बजे तक सभी आसपास की वॉयस रिकॉर्डिंग शुरू हो जाएगी।',
        paragraphFive: 'उन सभी लोगों को जिन्होंने आपका सहायता अनुरोध प्राप्त किया है, वे 12 घंटों तक या जब तक आप खुद को सुरक्षित नहीं कर लेते, तब तक गूगल मानचित्र पर अपना वास्तविक समय आंदोलन देख सकते हैं।',
        paragraphSix: 'तो एक बार "मैं सुरक्षित हूँ" बटन पर क्लिक करने के लिए मत भूलना जब आपको लगता है कि आप सुरक्षित हैं।',
        errorMsg: 'फ़ाइल अपलोड विफल रहा',
        retryUpload: 'अपलोड पुन: करें',
        uploadProgress: 'प्रगति अपलोड करें:',
        recordingUpload: 'रिकॉर्डिंग सफलतापूर्वक अपलोड की गई। अब अपने पसंदीदा को भेज रहे हैं।',
        women: 'महिला',
        blood: 'रक्त',
        child: 'बच्चा',
        emergencyScreenText: 'यहां आपको एप्लिकेशन के नवीनतम समाचार दिखाई देंगे',
        yourRequests: 'आपके अनुरोध',
        childRequests: 'बाल अनुरोध',
        submit: 'प्रस्तुत करना',
        uploadImage: 'तस्वीर डालिये',
        markAsFound: 'पाया के रूप में चिह्नित करें',
      }
    }
  },
  lng: "en",
  fallbackLng: "en",
  interpolation: {
    escapeValue: false
  }
});

export default i18n;
